# Generated by Django 6.0.6 on 2026-07-07 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_management', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_plate_text', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=10)),
                ('was_authorized', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('detection_source', models.CharField(choices=[('WEBCAM', 'Live Webcam'), ('UPLOAD', 'Image Upload'), ('MANUAL', 'Manual Entry')], default='WEBCAM', max_length=10)),
                ('captured_image', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='access_management.gate')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_entries', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='records_ent_timesta_04fc0e_idx'), models.Index(fields=['direction'], name='records_ent_directi_e018f1_idx')],
            },
        ),
    ]
