# Generated by Django 6.0.6 on 2026-07-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexitrecord',
            name='plate_image',
            field=models.ImageField(blank=True, null=True, upload_to='records/plate_crops/'),
        ),
    ]
