# Generated by Django 6.0.6 on 2026-07-14 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0001_initial'),
        ('records', '0002_entryexitrecord_plate_image'),
        ('vehicles', '0002_vehiclecompany_vehiclemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryexitrecord',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='records/full_frames/'),
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='detected_plate_text',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='detection_source',
            field=models.CharField(choices=[('WEBCAM', 'Live Webcam'), ('UPLOAD', 'Image Upload'), ('CCTV', 'CCTV Camera'), ('MANUAL', 'Manual Entry')], default='WEBCAM', max_length=10),
        ),
        migrations.AddIndex(
            model_name='entryexitrecord',
            index=models.Index(fields=['detected_plate_text'], name='records_ent_detecte_efaddb_idx'),
        ),
        migrations.AddIndex(
            model_name='entryexitrecord',
            index=models.Index(fields=['was_authorized'], name='records_ent_was_aut_a56dd0_idx'),
        ),
    ]
