# Generated by Django 5.2.16 on 2026-07-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_entryexitrecord_captured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexitrecord',
            name='detected_vehicle_company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entryexitrecord',
            name='detected_vehicle_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entryexitrecord',
            name='detected_vehicle_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='entryexitrecord',
            name='vehicle_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='entryexitrecord',
            name='vehicle_color_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entryexitrecord',
            name='vehicle_make_model_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entryexitrecord',
            name='vehicle_type_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
