# Generated by Django 6.0.6 on 2026-07-07 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('CLERK', 'Clerk'), ('VISITOR', 'Visitor')], max_length=20)),
                ('vehicle_company', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('FOUR_WHEELER', 'Four Wheeler'), ('HEAVY_VEHICLE', 'Heavy Vehicle')], default='TWO_WHEELER', max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('CNG', 'CNG'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('registration_number', models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must be in the format KA25AB1234.', regex='^[A-Z]{2}[0-9]{1,2}[A-Z]{1,3}[0-9]{4}$')])),
                ('registration_date', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('authorization_status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('UNAUTHORIZED', 'Unauthorized'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Review')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='access_management.department')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['registration_number'], name='vehicles_ve_registr_3774f3_idx'), models.Index(fields=['authorization_status'], name='vehicles_ve_authori_8fa086_idx')],
            },
        ),
    ]
