# Generated by Django 6.0.6 on 2026-07-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('FOUR_WHEELER', 'Four Wheeler'), ('HEAVY_VEHICLE', 'Heavy Vehicle')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['vehicle_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'vehicle_type'), name='unique_company_per_vehicle_type')],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclecompany')),
            ],
            options={
                'ordering': ['company__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_model_per_company')],
            },
        ),
    ]
