# Generated by Django 6.0.6 on 2026-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('CSD', 'Computer Science & Design'), ('AI', 'Artificial Intelligence'), ('ECE', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics'), ('MECHANICAL', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('ADMINISTRATION', 'Administration'), ('LIBRARY', 'Library')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('camera_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, unique=True)),
                ('can_manage_vehicles', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Campus Security System', max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('date_format', models.CharField(default='DD MMM YYYY', max_length=20)),
                ('time_format', models.CharField(choices=[('12_HOUR', '12 Hour'), ('24_HOUR', '24 Hour')], default='12_HOUR', max_length=10)),
                ('items_per_page', models.PositiveIntegerField(default=10)),
                ('anpr_confidence_threshold', models.FloatField(default=0.4)),
                ('auto_flag_unauthorized', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
