# Generated by Django 5.2.16 on 2026-07-19 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gate',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='gate',
            name='camera_name',
            field=models.CharField(blank=True, help_text='Example: Camera 1, Camera 2', max_length=100),
        ),
        migrations.AddField(
            model_name='gate',
            name='camera_source',
            field=models.CharField(choices=[('WEBCAM', 'USB Webcam'), ('IP_CAMERA', 'IP Camera'), ('CCTV', 'CCTV Camera')], default='WEBCAM', max_length=20),
        ),
        migrations.AddField(
            model_name='gate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gate',
            name='gate_type',
            field=models.CharField(choices=[('ENTRY', 'Entry Gate'), ('EXIT', 'Exit Gate')], default='ENTRY', max_length=10),
        ),
        migrations.AlterField(
            model_name='gate',
            name='camera_ip',
            field=models.CharField(blank=True, help_text='Required only for IP cameras', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
