# Generated by Django 5.2.16 on 2026-07-19 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0002_alter_gate_options_gate_camera_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='camera_device_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='OpenCV device index for laptop and USB cameras. The default camera is 0.', validators=[django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AddField(
            model_name='gate',
            name='crossing_direction',
            field=models.CharField(choices=[('ANY', 'Either Direction'), ('A_TO_B', 'Side A to Side B'), ('B_TO_A', 'Side B to Side A')], default='ANY', help_text='Allowed physical movement across the configured line. The gate type still controls whether the saved event is ENTRY or EXIT.', max_length=10),
        ),
        migrations.AddField(
            model_name='gate',
            name='line_crossing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='line_end_x',
            field=models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='gate',
            name='line_end_y',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='gate',
            name='line_start_x',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='gate',
            name='line_start_y',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='gate',
            name='target_fps',
            field=models.PositiveSmallIntegerField(default=10, help_text='Target camera processing rate.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='gate',
            name='camera_ip',
            field=models.CharField(blank=True, help_text='IP address, HTTP stream URL, or RTSP URL. Leave blank for local cameras.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='camera_source',
            field=models.CharField(choices=[('WEBCAM', 'Laptop/Web Camera'), ('USB_CAMERA', 'USB Camera'), ('IP_CAMERA', 'IP Camera'), ('RTSP', 'RTSP Stream'), ('CCTV', 'CCTV Camera'), ('VIDEO_UPLOAD', 'Uploaded Video')], default='WEBCAM', max_length=20),
        ),
    ]
